# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 09aaf72c229b3fce428fe3f4bdfb5d4bbf3e2f4220adb0af659283f69308850ae4e73ca2a8557f737deb421d97c4159f896818c34a76d6e4a4e8ce9b50b82458

test:
  secret_key_base: bac42dd9ccf42da2d4a849bfd3f8aa4bf036a6688c22be8d6e2f3f208b209128757584b2215a67c04a8bc2d16d2ed5aa98fa9a1283ae9db5f1610e6320789bed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
